[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]

solc = "0.8.20"
optimizer = true
optimizer-runs = 200
via_ir = true

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "single"
wrap_comments = false
override_spacing = true
